<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=emulateIE7" />
<meta name="keywords" content="ぱど基幹サブシステム,分析,部数表詳細" />
<meta name="description" content="ぱど基幹サブシステム 部数表詳細" />
<link rel="stylesheet" href="/html/css/common.css" type="text/css" />
<link rel="stylesheet" href="/html/css/style.css" type="text/css" />
<link rel="stylesheet" href="/html/css/jquery-ui-1.10.0.custom.css" type="text/css" />
<link rel="stylesheet" href="/html/css/ui.jqgrid.css" type="text/css" />
<script type="text/javascript" src="/html/js/jquery.js"></script>
<script type="text/javascript" src="/html/js/jquery-ui-1.10.0.custom.min.js"></script>
<script type="text/javascript" src="/html/js/jquery.jqGrid.min.js"></script>
<script type="text/javascript" src="/html/js/i18n/grid.locale-ja.js"></script>
<script type="text/javascript" src="/html/js/i18n/jquery.ui.datepicker-ja.js"></script>
<script type="text/javascript" src="/html/js/common.js"></script>
<script type="text/javascript" src="/html/js/blockUI.js"></script>

<script type="text/javascript">

$(function()
{
	var grid = JSON.stringify(<?= $this->arrdata ?>);
	document.frmMain.grid.value = grid;
});

</script>

<script type="text/javascript">

jQuery(document).ready(function()
{
	var arrdata = <?= $this->arrdata ?>;

	$('#list').jqGrid({
		data     : arrdata,
		datatype : 'local',
		colNames : [ '流通拠点', 'ブロック', 'エリア', '拠点コード', 'ブロックコード', 'エリアコード'],
		colModel : [ 
			{ name : 'base' , index : 'base', width:80},
			{ name : 'block', index : 'block',width:80, align:'center'},
			{ name : 'area' , index : 'area', width:150},
			{ name : 'kyocd' , index : 'kyocd' , hidden: true , width:30, align:'center'},
			{ name : 'blcd'  , index : 'blcd'  , hidden: true , width:30, align:'center'},
			{ name : 'areacd', index : 'areacd', hidden: true , width:30, align:'center'}
		],
		caption		: '部数表詳細',
		gridview    : true,
		rowNum      : 2000,
		sortname    : 'base,block',
		sortorder   : "asc",
		height		: 480,
		width       : 'auto',
		viewrecords : true,

		treeGrid     : true,
		treeGridModel: 'nested',
		treedatatype : 'local',
		multiselect  : true,
		scrollrows   : false,
		ongroupFieldClick: function(id){ alert("ああ"); },
		grouping	 : true,	//グルーピングを使用する
		groupingView : {		//グルーピングの設定
			groupField		 : ['base','block'], //グループ化したい項目
			groupText		 : ['<b>{0}</b>'], //グループ化した項目の表示名
			groupOrder 		 : ['asc'], //昇順
			groupColumnShow  : [true],
			groupSummary	 : [false]  //サマリータイプを使用する
		}
	});
});

</script>


<title>ぱど基幹サブシステム 部数表詳細</title>

</head>
<body>

	<form name="frmMain" action="circulationdetail" method="post">
		<input type="hidden" name="type" value="<?= $this->Type ?>">
		<input type="hidden" name="report" value="<?= $this->Report ?>">
		<input type="hidden" name="toymd" value="<?= $this->ToYmd ?>">
		<input type="hidden" name="fromymd" value="<?= $this->FromYmd ?>">
		<input type="hidden" name="token" value="<?= $this->Token ?>">
		<input type="hidden" name="grid">

		<div style="margin-top: 10px; margin-left: 10px;">
			<p><span class="required"><?= $this->ErrMsg ?></span></p>
			<table id="list"></table>
			<br>
			<table width="350">
				<tr align="right">
					<td>
						<input type="submit" name="btnPrint" id="btnPrint" class="button" value="出力" />
						<input type="button" name="btnCancel" id="btnCancel" class="button" value="キャンセル" onclick="window.close(); return false;" />
					</td>
				</tr>
			</table>
			<br>
		</div>
	</form>

</body>
</html>
