<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<meta http-equiv="X-UA-Compatible" content="IE=emulateIE7" />
<meta name="keywords" content="新基幹サブシステム,分析,部数表" />
<meta name="description" content="新基幹サブシステム 部数表出力" />
<link rel="stylesheet" href="/html/css/common.css" type="text/css" />
<link rel="stylesheet" href="/html/css/style.css" type="text/css" />
<link rel="stylesheet" href="/html/css/jquery-ui-1.10.0.custom.css" >
<script type="text/javascript" src="/html/js/jquery.js"></script>
<script type="text/javascript" src="/html/js/common.js"></script>
<script type="text/javascript" src="/html/js/jquery-ui-1.10.0.custom.js"></script>

<title>新基幹サブシステム 部数表</title>

<script language=javascript>
<!--

// Window Open sub window
function btnDetail_onclick() {
  var child = "http://localhost/PADO/analysis/circulationdetail/"; 
  subwin = window.open(child,"subWin","width=700,height=500,scrollbars=yes");
}

//-->
</script>

</head>
<body>

<!-- #top start -->
<div id="top">

	<!-- #header include -->
	<? @include("html/include/header.inc"); ?>

	<!-- #header menu include -->
	<? @include("html/include/headermenu.php"); ?>

	<!-- #contents start -->
	<div id="contents">

		<!-- #submenu include -->
		<? @include("html/include/submenu.php"); ?>

		<!-- #main start -->
		<div id="main2">
			<h2>部数表</h2>
			<p>ブロック表、地区表、担当地区表を出力する</p>
			<ul class="button-group">
				<li><button class="large button">ブロック表(Excel)</button></li>
				<li><button class="large button">地区表(Excel)</button></li>
				<li><button class="large button">担当地区表(CSV)</button></li>
			</ul><br>
			<form method="post" action="./confirm.php" enctype="multipart/form-data">
				<input type="hidden" name="form" value="1" />
				<!-- #formAreaInner start -->
				<div id="formAreaInner" clearfix">
					<table>
						<tr>
							<th width="100">掲載版<span class="required">(必須)</span></th>
							<td>
								<select id="select" multiple="multiple" >
									<option value="0">011:首都圏直営版</option>
									<option value="1">015:京阪北版</option>
									<option value="2">016:北摂東版</option>
								</select>
							</td>
						</tr>
						<tr>
							<th>期間<span class="required">(必須)</span></th>
							<td>
								<input type="hidden" id="selectItemsSave" />
								<select id="select">
									<option value="0">2013/02/01～</option>
								</select>
							</td>
						</tr>
						<tr><th colspan="2">お知らせ</th></tr>
						<tr>
							<td colspan="2">
								<textarea disabled cols="77" id="txtOther"></textarea>
							</td>
						</tr>
					</table>
				</div>
				<!-- #formAreaInner end -->

				<div id="formBtnArea" class="FormBtnArea">
					<table width="1100">
						<tr>
							<td>
								<input type="button" id="btnDetail" class="button" value="詳細" onclick="btnDetail_onclick()" />
								<input type="button" class="button" value="出力" onclick="" />
								<!--<input type="button" value="参照" onclick="void(this.form.submit());return false" class="ConfBtn"/>
								<input type="image" onclick="void(this.form.submit());return false" alt="" class="ConfBtn" src="../../html/image/confirm.png" />-->
							</td>
						</tr>
					</table>
				</div>
				</br>
			</form>
		</div>
		<!-- #main end -->

	</div>
	<!-- #contents end -->
	
	<!-- #header include -->
	<? @include("html/include/footer.inc"); ?>

</div>
<!-- #top end -->

</body>
</html>
