<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" lang="ja">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<link rel="stylesheet" href="/html/css/common.css" type="text/css" />
<link rel="stylesheet" href="/html/css/style.css" type="text/css" />
<link rel="stylesheet" href="/html/css/jquery-ui-1.10.0.custom.css" >
<script type="text/javascript" src="/html/js/jquery.js"></script>
<script type="text/javascript" src="/html/js/common.js"></script>
<script type="text/javascript" src="/html/js/jquery-ui-1.10.0.custom.js"></script>

<title>新基幹サブシステム</title>
<!--[if lt IE 7]>
<script src="http://ie7-js.googlecode.com/svn/version/2.0(beta3)/IE7.js" type="text/javascript"></script>
<![endif]-->

</head>

<body>
<!-- #top start -->
<div id="top">

	<!-- #header include -->
	<? @include("html/include/header.inc"); ?>

	<!-- #header menu include -->
	<? @include("html/include/headermenu.php"); ?>
	
	<!-- #contents start -->
	<div id="contents">

		<!-- #submenu include -->
		<? @include("html/include/submenu.php"); ?>

		<!-- #main start -->
		<div id="main2">
		<form name="frmMain" action="index" method="post">
			<input type="hidden" name="url" value="<?= $this->Token ?>">
			<h2>テスト大見出し</h2>
			<p>テスト内容テスト内容テスト内容テスト内容テスト内容テスト内容テスト内容テスト内容</p>
			<p>現在表示しているページに該当するメニューのa要素に｢class="active"｣を指定すると、メニューボタンの色が変わり、ナビゲーションの役割を果たします。</p>
			<h3>画像について</h3>
			<p>画像色の変更などの編集も可能です。</p>
			<h3>ページ上部への戻りリンクについて</h3>
			<p>ページ上部への戻りは、JavaScriptによりなめらかにスクロールしながら移動するようにしてます。</p>
			<h3>カスタマイズについて</h3>
			<p>ご自由にどーぞ</p>
			<p>その他、不具合などございましたら相原まで☆</p>
			<h2>サンプルタグについて</h2>
			<p>以下、サンプルタグです</p>
			<h3>INFORMATION</h3>
			<dl class="information">
			<dt><span>2011-01-01</span></dt>
			<dd>
				<div>
					テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト。<br />
				</div>
			</dd>
			<dt><span>2011-01-23</span></dt>
			<dd>
				<div>
					テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト。<br />
				</div>
			</dd>
			</dl>
			<h3>h3タグ</h3>
			<h4>h4タグ</h4>
			<h5>h5タグ</h5>
			<h6>h6タグ</h6>
			<p>
			<em>強調</em>
			<strong>より強い強調</strong>
			<ins>追加</ins>
			<del>削除</del>
			<br />
			<a href="#">テキストアンカー</a>
			</p>
			<h4>リスト</h4>
			<h5>普通のリスト</h5>
			<ul>
				<li>普通のリスト1</li>
				<li>普通のリスト2</li>
				<li>普通のリスト3</li>
			</ul>
			<h5>番号付きリスト</h5>
			<ol>
				<li>番号付きリスト1</li>
				<li>番号付きリスト2</li>
				<li>番号付きリスト3<br />li要素の中はブロックレベルのタグを使用することが出来ます。例えば、&lt;p&gt;タグも記述することが出来ます。<br /></li>
			</ol>
			<h5>定義リスト</h5>
			<dl>
				<dt>定義リスト1</dt>
				<dd>定義した用語の説明</dd>
				<dt>定義リスト2</dt>
				<dd>定義した用語の説明</dd>
				<dt>定義リスト3</dt>
				<dd>定義した用語の説明<br />dd要素の中はブロックレベルのタグを使用することが出来ます。例えば、&lt;p&gt;タグも記述することが出来ます。しかし、dt要素にはインライン要素しか記述することができません。</dd>
			</dl>
			<h4>テーブル</h4>
			<div id="formAreaInner">
				<table>
					<tr><th>見出し1</th><th>見出し2</th><th>見出し3</th><th>見出し4</th><th>見出し5</th></tr>
					<tr><td>セル1</td><td>セル2</td><td>セル3</td><td>セル4</td><td>セル5</td></tr>
					<tr><td>セル1</td><td>セル2</td><td>セル3</td><td>セル4</td><td>セル5</td></tr>
					<tr><td>セル1</td><td>セル2</td><td>セル3</td><td>セル4</td><td>セル5</td></tr>
				</table>
			</div>

			<h4 style="margin-top: 11em;">ボタン</h4>
			小さいボタン<button class="small button">Button</button>&nbsp;&nbsp;
			大きいボタン<button class="large button">Button</button><br>
			ボタングルー化<br>
			<ul class="button-group">
			    <li><button class="button">Button</button></li>
			    <li><button class="button">Button</button></li>
			    <li><button class="button">Button</button></li>
			    <li><button class="button">Button</button></li>
			</ul>

			<h4>JQueyButton</h4>
			<button id="button">A button element</button>
			<form style="margin-top: 2em;">
			<p><a href="" id="dialog-link" class="ui-state-default ui-corner-all">
				<span class="ui-icon ui-icon-newwin"></span>Open Dialog
			</a></p>
			<!-- ui-dialog -->
			<div id="dialog" title="Dialog Title">
				<p>登録しますか？</p>
			</div>
			</form>
			<form style="margin-top: 2em;">
				<div id="radioset">
					<input type="radio" id="radio1" name="radio"><label for="radio1">Choice 1</label>
					<input type="radio" id="radio2" name="radio" checked="checked"><label for="radio2">Choice 2</label>
					<input type="radio" id="radio3" name="radio"><label for="radio3">Choice 3</label>
				</div>
			</form>
			<br>
			<h4>Progressbar</h4>
			<div id="progressbar"></div>
			<br>
			<h4>Datepicker</h4>
			<div id="datepicker"></div>
		</form>
		</div>

		<!-- #main end -->
		<div id="pageTop">
			<a href="#">ページのトップへ戻る</a>
		</div>
	</div>
	<!-- #contents end -->

	<!-- #header include -->
	<? @include("html/include/footer.inc"); ?>

</div>
<!-- #top end -->

</body>
</html>