<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<meta http-equiv="X-UA-Compatible" content="IE=emulateIE7" />
<meta name="keywords" content="ぱど基幹サブシステム,エラー" />
<meta name="description" content="ぱど基幹サブシステム エラー" />
<link rel="stylesheet" href="/html/css/common.css" type="text/css" />
<link rel="stylesheet" href="/html/css/style.css" type="text/css" />
<script type="text/javascript" src="/html/js/jquery.js"></script>
<script type="text/javascript" src="/html/js/common.js"></script>
<title>ぱど基幹サブシステムエラー</title>
</head>

<body>
	<h1>An error occurred</h1>
	<h2><?php echo $this->message ?></h2>

	<?php if (isset($this->exception)): ?>

	<h3>Exception information:</h3>
	<p>
	  <b>Message:</b> <?php echo $this->exception->getMessage() ?>
	</p>

	<h3>Stack trace:</h3>
	<pre><?php echo $this->exception->getTraceAsString() ?>
	</pre>

	<h3>Request Parameters:</h3>
	<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
	</pre>

	<?php endif ?>
</body>
</html>
