<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<meta http-equiv="X-UA-Compatible" content="IE=emulateIE7" />
<meta name="keywords" content="新基幹システム,会社マスタ,組織" />
<meta name="description" content="新基幹システム 会社情報の登録・削除" />
<link rel="stylesheet" href="/html/css/common.css" type="text/css" />
<link rel="stylesheet" href="/html/css/style.css" type="text/css" />
<link rel="stylesheet" href="/html/css/jquery-ui-1.10.0.custom.css" >
<script type="text/javascript" src="/html/js/jquery.js"></script>
<script type="text/javascript" src="/html/js/common.js"></script>
<script type="text/javascript" src="/html/js/jquery-ui-1.10.0.custom.js"></script>

<!--[if lt IE 7]>
<script src="http://ie7-js.googlecode.com/svn/version/2.0(beta3)/IE7.js" type="text/javascript"></script>
<![endif]-->

<title>新基幹サブシステム 会社マスタ</title>

</head>
<body>

<!-- #top start -->
<div id="top">

	<!-- #header include -->
	<? @include("html/include/header.inc"); ?>

	<!-- #header menu include -->
	<? @include("html/include/headermenu.php"); ?>
	
	<!-- #contents start -->
	<div id="contents">

		<!-- #submenu include -->
		<? @include("html/include/submenu.php"); ?>

		<!-- #main start -->
		<div id="main2">
			<h2>会社マスタ</h2>
			<p>会社情報を登録、更新・削除する</p>
			<p><span class="required"><?= $this->ErrMsg ?></span></p>
			<form method="post" action="./confirm.php" enctype="multipart/form-data">

				<!-- #formAreaInner start -->
				<div id="formAreaInner">
					<table>
						<tr>
							<th>会社コード</th>
							<td>
								<input type="text" id="txtCompanyCd" value="<?= $this->CompanyCd ?>" size="10" maxlength="3" />
								<input type="button" id="btnCompany" value="参照" onclick="" />
							</td>
						</tr>
						<tr>
							<th>会社名称<span class="required">(必須)</span></th>
							<td><input type="text" id="txtCompanyName" value="" size="100" maxlength="100" /></td>
						</tr>
						<tr>
							<th>会社名カナ</th>
							<td><input type="text" id="txtCompanyNameKana" value="" size="100" maxlength="100" /></td>
						</tr>
						<tr>
							<th>会社略称</th>
							<td><input type="text" id="txtCompanySName" value="" size="50" maxlength="40" /></td>
						</tr>
						<tr>
							<th>住所</th>
							<td>
								<table class="noborder">
									<tr>
										<td>郵便番号</td>
										<td width="150"><input type="text" id="txtZipCd" value="" size="20" maxlength="8" onKeyUp="AjaxZip2.zip2addr(this,'pref','txtAddress1');" /></td>
										<td width="60">都道府県</td>
										<td><select id="pref">
											<option value="">選択</option>
											<option value="北海道">北海道</option><option value="青森県">青森県</option>
											<option value="岩手県">岩手県</option><option value="宮城県">宮城県</option>
											<option value="秋田県">秋田県</option><option value="山形県">山形県</option>
											<option value="福島県">福島県</option><option value="茨城県">茨城県</option>
											<option value="栃木県">栃木県</option><option value="群馬県">群馬県</option>
											<option value="埼玉県">埼玉県</option><option value="千葉県">千葉県</option>
											<option value="東京都">東京都</option><option value="神奈川県">神奈川県</option>
											<option value="新潟県">新潟県</option><option value="富山県">富山県</option>
											<option value="石川県">石川県</option><option value="福井県">福井県</option>
											<option value="山梨県">山梨県</option><option value="長野県">長野県</option>
											<option value="岐阜県">岐阜県</option><option value="静岡県">静岡県</option>
											<option value="愛知県">愛知県</option><option value="三重県">三重県</option>
											<option value="滋賀県">滋賀県</option><option value="京都府">京都府</option>
											<option value="大阪府">大阪府</option><option value="兵庫県">兵庫県</option>
											<option value="奈良県">奈良県</option><option value="和歌山県">和歌山県</option>
											<option value="鳥取県">鳥取県</option><option value="島根県">島根県</option>
											<option value="岡山県">岡山県</option><option value="広島県">広島県</option>
											<option value="山口県">山口県</option><option value="徳島県">徳島県</option>
											<option value="香川県">香川県</option><option value="愛媛県">愛媛県</option>
											<option value="高知県">高知県</option><option value="福岡県">福岡県</option>
											<option value="佐賀県">佐賀県</option><option value="長崎県">長崎県</option>
											<option value="熊本県">熊本県</option><option value="大分県">大分県</option>
											<option value="宮崎県">宮崎県</option><option value="鹿児島県">鹿児島県</option>
											<option value="沖縄県">沖縄県</option>
										</select></td>
									</tr>
									<tr>
										<td>市区町村</td>
										<td colspan="3"><input type="text" id="txtAddress1" size="100" maxlength="100" /></td>
									</tr>
									<tr>
										<td>ビル</td>
										<td colspan="3"><input type="text" id="txtAddress2" size="100" maxlength="100" /></td>
									</tr>
								</table>
								
							</td>
						<tr>
							<th>ＴＥＬ</th>
							<td><input type="text" id="txtTel" value="" size="30" maxlength="20" /></td>
						</tr>
						<tr>
							<th>ＦＡＸ</th>
							<td><input type="text" id="txtFax" value="" size="30" maxlength="20" /></td>
						</tr>
						<tr>
							<th>親会社</th>
							<td>
								<input type="text" id="txtPCompanyCd" value="" size="10" maxlength="3" />
								<input type="button" id="btnCompany" value="参照" onclick="" />
								<input type="text" id="txtPCompanyName" value="" size="90" maxlength="100" />
							</td>
						</tr>
						<tr>
							<th>収納代行業者</th>
							<td>
								<input type="text" id="txtAgencyCd" value="" size="10" maxlength="4" />
								<input type="button" id="btnAgency" value="参照" onclick="" />
								<input type="text" id="txtAgencyName" value="" size="90" maxlength="100" />
							</td>
						</tr>
						<tr>
							<th>口座振替業者</th>
							<td>
								<input type="text" id="txtATTradeCd" value="" size="10" maxlength="4" />
								<input type="button" id="btnATTrade" value="参照" onclick="" />
								<input type="text" id="txtATTradeName" value="" size="90" maxlength="100" />
							</td>
						</tr>
						<tr>
							<th>振込手数料上限</th>
							<td><input type="text" id="txtMaxfee" value="" size="30" maxlength="18" />&nbsp;円</td>
						</tr>
						<tr>
							<th>金額端数区分</th>
							<td>
								<input type="text" id="txtAFractionCd" value="" size="10" maxlength="2" />
								<input type="button" id="btnAFraction" value="参照" onclick="" />
								<input type="text" id="txtAFractionName" value="" size="50" maxlength="50" />
							</td>
						</tr>
						<tr>
							<th>消費税端数区分</th>
							<td>
								<input type="text" id="txtTFractionCd" value="" size="10" maxlength="2" />
								<input type="button" id="btnTFraction" value="参照" onclick="" />
								<input type="text" id="txtTFractionName" value="" size="50" maxlength="50" />
							</td>
						</tr>
						<tr><th colspan="2">口座情報</th></tr>
						<tr>
							<th rowspan="2">請求</th>
							<td>
								<table class="noborder">
									<tr>
										<td width="80">銀行</td>
										<td width="100"><input type="text" id="txtBankName1" class="DisabledArea" value="" size="20" maxlength="10" /></td>
										<td class="right">支店</td>
										<td><input type="text" id="txtBBankName1" class="DisabledArea" value="" size="20" maxlength="10" /></td>
										<td class="right" width="60">口座区分</td>
										<td><input type="text" id="txtAccountKbn1" class="DisabledArea" value="" size="20" maxlength="10" /></td>
									</tr>
									<tr>
										<td>引落口座</td>
										<td><input type="text" id="txtDAccountCd" value="" size="20" maxlength="10" /></td>
										<td><input type="button" id="btnDAccount" value="参照" onclick="" /></td>
										<td colspan="3"><input type="text" name="txtDAccountName" value="" size="60" maxlength="50" /></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td>
								<table class="noborder">
									<tr>
										<td width="80">銀行</td>
										<td width="100"><input type="text" id="txtBankName2" class="DisabledArea" value="" size="20" maxlength="10" /></td>
										<td class="right">支店</td>
										<td><input type="text" id="txtBBankName2" class="DisabledArea" value="" size="20" maxlength="10" /></td>
										<td class="right" width="60">口座区分</td>
										<td><input type="text" id="txtAccountKbn2" class="DisabledArea" value="" size="20" maxlength="10" /></td>
									</tr>
									<tr>
										<td>振込使用口座</td> 
										<td><input type="text" id="txtTAccountCd" value="" size="20" maxlength="10" /></td>
										<td><input type="button" id="btnTAccount" value="参照" onclick="" /></td>
										<td colspan="3"><input type="text" name="txtTAccountName" value="" size="60" maxlength="50" /></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<th>支払</th>
							<td>
								<table class="noborder">
									<tr>
										<td width="80">銀行</td>
										<td width="100"><input type="text" id="txtBankName3" class="DisabledArea" value="" size="20" maxlength="10" /></td>
										<td class="right">支店</td>
										<td><input type="text" id="txtBBankName3" class="DisabledArea" value="" size="20" maxlength="10" /></td>
										<td class="right" width="60">口座区分</td>
										<td><input type="text" id="txtAccountKbn3" class="DisabledArea" value="" size="20" maxlength="10" /></td>
									</tr>
									<tr>
										<td>支払口座</td> 
										<td><input type="text" id="txtPAccountCd" value="" size="20" maxlength="10" /></td>
										<td><input type="button" id="btnPAccount" value="参照" onclick="" /></td>
										<td colspan="3"><input type="text" name="txtPAccountName" value="" size="60" maxlength="50" /></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<th rowspan="3">仮想口座</th>
							<td>
								<table class="noborder">
									<tr>
										<td width="80">銀行</td> 
										<td><input type="text" id="txtBankCd4" value="" size="20" maxlength="10" /></td>
										<td><input type="button" id="btnBankName4" value="参照" onclick="" /></td>
										<td><input type="text" name="txtBankName4" value="" size="60" maxlength="50" /></td>
									</tr>
									<tr>
										<td width="80">支店</td> 
										<td><input type="text" id="txtBBankCd4" value="" size="20" maxlength="10" /></td>
										<td><input type="button" id="btnBBankCd4" value="参照" onclick="" /></td>
										<td><input type="text" name="txtBBankName4" value="" size="60" maxlength="50" /></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<th>実口座</th>
						</tr>
						<tr>
							<td>
								<table class="noborder">
									<tr>
										<td width="80">銀行</td>
										<td width="100"><input type="text" id="txtBankName5" class="DisabledArea" value="" size="20" maxlength="10" /></td>
										<td class="right">支店</td>
										<td><input type="text" id="txtBBankName5" class="DisabledArea" value="" size="20" maxlength="10" /></td>
										<td class="right" width="60">口座区分</td>
										<td><input type="text" id="txtAccountKbn5" class="DisabledArea" value="" size="20" maxlength="10" /></td>
									</tr>
									<tr>
										<td>口座</td> 
										<td><input type="text" id="txtAccountCd" value="" size="20" maxlength="10" /></td>
										<td><input type="button" id="btnAccount" value="参照" onclick="" /></td>
										<td colspan="3"><input type="text" name="txtAccountName" value="" size="60" maxlength="50" /></td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</div>
				<!-- #formAreaInner end -->

				<div id="formBtnArea" class="FormBtnArea clearfix">
					<table>
						<tr>
							<td><!--
								<input type="button" class="button" value="登録" onclick="" />
								<input type="button" class="button" value="更新" onclick="" />
								<input type="button" class="button" value="削除" onclick="" />
								<input type="button" value="参照" onclick="void(this.form.submit());return false" class="ConfBtn"/>
								<input type="image" onclick="void(this.form.submit());return false" alt="" class="ConfBtn" src="../../html/image/confirm.png" />-->
							</td>
						</tr>
					</table>
				</div>
				</br>
			</form>
		</div>
		<!-- #main end -->

	</div>
	<!-- #contents end -->
	
	<!-- #header include -->
	<? @include("html/include/footer.inc"); ?>

</div>
<!-- #top end -->

</body>
</html>
